const STEPS = [
  {
    number: '01',
    title: 'Input your content',
    description: 'Paste text directly or enter a URL. MianTrace fetches and extracts the main content from webpages automatically.',
  },
  {
    number: '02',
    title: 'Signal analysis',
    description: 'Eight writing signals are measured — sentence uniformity, vocabulary diversity, phrase repetition, structural predictability, and more.',
  },
  {
    number: '03',
    title: 'Weighted scoring',
    description: 'Signals are weighted and combined into an AI-likelihood estimate with a confidence level based on text length and signal agreement.',
  },
  {
    number: '04',
    title: 'Explained results',
    description: 'Every signal is explained, not just scored. MianTrace also provides improvement suggestions — not just a verdict.',
  },
]

export function HowItWorks() {
  return (
    <section
      id="how-it-works"
      className="py-16 px-4 border-t border-gray-100 dark:border-gray-800"
      aria-labelledby="how-it-works-heading"
    >
      <div className="max-w-5xl mx-auto">
        <div className="text-center mb-12">
          <h2
            id="how-it-works-heading"
            className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white mb-3"
          >
            How It Works
          </h2>
          <p className="text-gray-500 dark:text-gray-400 max-w-md mx-auto">
            A transparent, signal-based approach. No black boxes, no false certainty.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {STEPS.map((step, i) => (
            <div key={step.number} className="relative">
              {/* Connector line */}
              {i < STEPS.length - 1 && (
                <div
                  className="hidden lg:block absolute top-5 left-full w-full h-px bg-gray-200 dark:bg-gray-700 -translate-x-4 z-0"
                  aria-hidden="true"
                />
              )}

              <div className="relative z-10">
                <div className="w-10 h-10 rounded-xl bg-indigo-50 dark:bg-indigo-950 border border-indigo-100 dark:border-indigo-900 flex items-center justify-center mb-4">
                  <span className="text-xs font-bold text-indigo-600 dark:text-indigo-400">
                    {step.number}
                  </span>
                </div>
                <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-1.5">
                  {step.title}
                </h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed">
                  {step.description}
                </p>
              </div>
            </div>
          ))}
        </div>

        {/* Limitation note */}
        <div className="mt-12 p-4 rounded-xl bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 text-center">
          <p className="text-sm text-gray-500 dark:text-gray-400 max-w-2xl mx-auto">
            <span className="font-medium text-gray-700 dark:text-gray-300">Important: </span>
            MianTrace provides a probabilistic analysis based on writing patterns. It cannot prove
            whether content was written by a human or generated by AI. Results should be used as one
            signal among many, not as a definitive verdict.
          </p>
        </div>
      </div>
    </section>
  )
}
