/**
 * report.ts
 * Generates a clean plain-text analysis report from an AnalysisResult.
 * Used by the "Copy Report" button — no backend, pure frontend.
 */

import type { AnalysisResult, Signal } from '../types'

const LEVEL_LABEL: Record<string, string> = {
  high:   'High',
  medium: 'Medium',
  low:    'Low',
}

const CONFIDENCE_LABEL: Record<string, string> = {
  high:     'High',
  moderate: 'Moderate',
  low:      'Low',
}

function divider(char = '─', len = 44): string {
  return char.repeat(len)
}

function signalLine(signal: Signal): string {
  const level = LEVEL_LABEL[signal.level] ?? signal.level
  const padding = 28 - signal.name.length
  return `  ${signal.name}${' '.repeat(Math.max(1, padding))}${level}`
}

/**
 * Generate a plain-text report from an AnalysisResult.
 * Suitable for clipboard copy.
 */
export function generateReport(result: AnalysisResult): string {
  const lines: string[] = []
  const { aiLikelihood, confidence, statistics, signals, explanation } = result

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push('MianTrace Analysis Report')
  lines.push(divider())
  lines.push(`Generated: ${new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })}`)

  // Website source line
  if (result.sourceMode === 'website' && result.websiteData) {
    lines.push(`Source: ${result.websiteData.url}`)
    if (result.websiteData.title) {
      lines.push(`Page: ${result.websiteData.title}`)
    }
  }

  lines.push('')

  // ── Score ───────────────────────────────────────────────────────────────────
  lines.push('AI-LIKELIHOOD ESTIMATE')
  lines.push(divider())
  lines.push(`Score:      ${aiLikelihood}%`)
  lines.push(`Confidence: ${CONFIDENCE_LABEL[confidence] ?? confidence}`)
  lines.push('')

  // ── Content overview ─────────────────────────────────────────────────────────
  lines.push('CONTENT OVERVIEW')
  lines.push(divider())
  lines.push(`Words:          ${statistics.words.toLocaleString()}`)
  lines.push(`Characters:     ${statistics.characters.toLocaleString()}`)
  lines.push(`Sentences:      ${statistics.sentences.toLocaleString()}`)
  lines.push(`Paragraphs:     ${statistics.paragraphs.toLocaleString()}`)
  lines.push(`Avg sentence:   ${statistics.avgSentenceLength} words`)
  lines.push(`Vocabulary:     ${Math.round(statistics.vocabularyDiversity * 100)}% unique words`)
  lines.push('')

  // ── Signals ─────────────────────────────────────────────────────────────────
  lines.push('WRITING SIGNALS')
  lines.push(divider())

  // Sort: high → medium → low
  const order: Record<string, number> = { high: 0, medium: 1, low: 2 }
  const sorted = [...signals].sort((a, b) => (order[a.level] ?? 3) - (order[b.level] ?? 3))

  for (const signal of sorted) {
    lines.push(signalLine(signal))
  }
  lines.push('')

  // ── Key finding ─────────────────────────────────────────────────────────────
  const highSignals = signals.filter(s => s.level === 'high')
  if (highSignals.length > 0) {
    lines.push('HIGH SIGNALS DETECTED')
    lines.push(divider())
    for (const s of highSignals) {
      lines.push(`• ${s.name}`)
      lines.push(`  ${s.description}`)
      if (s.suggestion) {
        lines.push(`  Suggestion: ${s.suggestion}`)
      }
      lines.push('')
    }
  }

  // ── Summary ──────────────────────────────────────────────────────────────────
  lines.push('SUMMARY')
  lines.push(divider())
  lines.push(explanation)
  lines.push('')

  // ── Limitation ──────────────────────────────────────────────────────────────
  lines.push('IMPORTANT')
  lines.push(divider())
  lines.push(
    'MianTrace provides a probabilistic analysis based on writing patterns. ' +
    'It cannot prove whether content was written by a human or generated by AI. ' +
    'Results are estimates, not proof of authorship.'
  )
  lines.push('')

  // ── Footer ───────────────────────────────────────────────────────────────────
  lines.push(divider('─', 44))
  lines.push('Generated by MianTrace')
  lines.push('https://mianhassam96.github.io/MianTrace/')

  return lines.join('\n')
}
